### ISSUE TITLE
ACT Status: ConnectionFailed

### ISSUE THREAD

**Issue by Reynbow** [lichie567/LMeter#31]
don't know where to reach out for help with this so here I am
nothing I do seems to be able to resolve this error
hope I can get some assistance
![image](https://user-images.githubusercontent.com/19285509/184362957-e023b342-981d-400a-997c-77b4804dc220.png)

**Comment by WreckingBear** [comment]
Do you use ACT with the ngld's OverlayPlugin? (Since this is, as far as I know, the current way to go)

If so - did you start the local overlay? (Plugins - OberlayPlugin WSServer - Stream/Local Overlay)

![image](https://user-images.githubusercontent.com/70053557/185725787-089bd544-964b-4b9a-9516-51f7e6cc1282.png)

If you did start it, check your Windows Firewall.

**Comment by joker-119** [comment]
I'm getting this issue ever since 6.2, worked fine before that.

**Comment by coolyc3** [comment]
I am also having issues since 6.2.
